// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDcb-Eemt9oDvZJnHXN9bJEEIQdS-9ero',
    appId: '1:579627162120:web:6e842d659476a8b0b6cfbd',
    messagingSenderId: '579627162120',
    projectId: 'anoopjose',
    authDomain: 'anoopjose.firebaseapp.com',
    storageBucket: 'anoopjose.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Wtz2V41JSjqAvNqxJyVoVSSqXgqJECQ',
    appId: '1:579627162120:android:8609a536ed5ba72db6cfbd',
    messagingSenderId: '579627162120',
    projectId: 'anoopjose',
    storageBucket: 'anoopjose.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATSiB-cL3HM0MUqzUHx6Upzr69Am9jgmQ',
    appId: '1:579627162120:ios:f904eb18467e5827b6cfbd',
    messagingSenderId: '579627162120',
    projectId: 'anoopjose',
    storageBucket: 'anoopjose.appspot.com',
    iosBundleId: 'co.uk.flutterly.snuggleTales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATSiB-cL3HM0MUqzUHx6Upzr69Am9jgmQ',
    appId: '1:579627162120:ios:f18c902ff0f980ddb6cfbd',
    messagingSenderId: '579627162120',
    projectId: 'anoopjose',
    storageBucket: 'anoopjose.appspot.com',
    iosBundleId: 'co.uk.flutterly.snuggleTales.RunnerTests',
  );
}
